rgbd_odometry:
  ros__parameters:
    frame_id: base_footprint
    odom_frame_id: vo_odom
    publish_tf: true
    wait_for_transform: 0.3
    wait_imu_to_init: true
    always_check_imu_tf: true
    keep_color: true
    publish_null_when_lost: false
    Reg/Force3DoF: 'true'
    guess_frame_id: odom
    Odom/ResetCountdown: '10'

rtabmap:
  ros__parameters:
    frame_id: base_footprint
    odom_frame_id: vo_odom
    map_frame_id: map
    publish_tf: true
    tf_tolerance: 0.3
    wait_for_transform: 0.3
    # database_path: /home/alien/.ros/small_office_rtabmap.db
    delete_db_on_start: false
    subscribe_scan: true
    Reg/Force3DoF: 'true'
    Reg/Strategy: '2'
